zsh -> bash,  direct use of zabbix keys, bugs

diff --git a/similish b/similish
--- a/similish
+++ b/similish
@@ -1,13 +1,12 @@
-#!/usr/bin/env zsh
 #!/usr/bin/env bash
 # ==============================================================================
 # bash read function does not behave the way I'm used to
 # A similish based on zabbix agent
 #
 # This is more a Proof of Concept for now than a reliable tool
-# Not sure if or how it might be useful
+#
 # Update: it may me really useful on the field
-# (well, at least once, at least for me)
+# (well, at least once, at least for me), modulo the numerous bugs
 #
 # ==============================================================================
 # TODO
@@ -19,14 +18,18 @@
 # - ltr: doit 
 # - handle commands parameters : ls, grep ...
 # - handle a larger number of arguments than 4
+# - IN PROGRESS Possibility of calling zabbix key directly (ex: agent.version)
 #
 # - colorize in general => colorlib.sh
 # - use a $HOME/.zashrc ?
 # - a kind of top
 # - handling logs (grep: sort of)
-
-# Possibility of writing name  of zabbix key directly
-# 
+#
+# CHERRY ON THE CAKE:
+# - implement Ctrl-D to bail out (how ?)
+# - implement command completion ??
+# - implement a kind of history
+#
 # ------------------------------------------------------------------------------
 # BUGS
 # - FIXED put a maxdepth param in vdg commands
@@ -44,14 +47,15 @@
 
 HOST=${1:-127.0.0.1}
 
-VERSION="0.5c (10-02-2026 morning)"
+VERSION="0.5f (10-02-2026 afternoon)"
 
 DEBUG="1"
 DEBUG=""
 
 TIMEOUT=4
 
-PROGNAME=$(basename $0)
+# In this script we use SCRIPTNAME, as PROGRAM_NAME is already used for prompt
+SCRIPTNAME=$(basename $0)
 
 # Not decided yet! SimiliSH sounds funnier in french, but
 # Zash is shorter and more logical
@@ -59,6 +63,9 @@ PROGRAM_NAME="SimiliSH"
 PROGRAM_NAME="ZaSH"
 
 PROMPT="${PROGRAM_NAME}> "
+
+GRID_STYLE=grid
+GRID_STYLE=plain
 
 # Set to null if system.run disact
 #EXTENDED_COMMANDS=""
@@ -69,8 +76,8 @@ CWD="/tmp"
 
 JQ_LL_EXTRACTOR="{type:.type, perms:.permissions, user:.user, group:.group, size:.size, datetime:.time.change, name:.basename}"
 
-# TO BE DEFINED
-#JQ_PS_EXTRACTOR="{type:.type, perms:.permissions, user:.user, group:.group, size:.size, datetime:.time.change, name:.basename}"
+JQ_PS_EXTRACTOR="{pid:.pid, name:.name, user:.user, vsize:.vsize, rss:.rss, cmdline:.cmdline}"
+JQ_PS_SORT_KEY=".rss"
 
 # Maintain value of zabbix
 # ==============================================================================
@@ -80,9 +87,9 @@ function usage {
 
     cat <<EOF
 
-    $PROGNAME: usage:
+    $SCRIPTNAME: usage:
 
-    $PROGNAME is a minimal read only shell (sort of) based on zabbix agent
+    $SCRIPTNAME is a minimal read only shell (sort of) based on zabbix agent
     various keys (vfs.dir.get, vfs.file.*, system.run if avail., etc ...)
 
     Not implemented: pipes, completion, modifications, awk, sed ...
@@ -95,7 +102,7 @@ function usage {
 EOF
 }
 
-# TBD k
+# TBD 
 function cleanup {
     rm -f tmp.json out.dat
 }
@@ -116,15 +123,21 @@ function display_welcome_message {
     echo
 }
 
-function help {
 
+function help {
     cat<<EOF
+    ## A 'shell' (sort of) based on zabbix agent capabilities ###
     # Some commands:
      pwd: display current directory
      cd:  change current directory
      ls:  display content of current directory
      cat: display content of given file
      {ck|md5}sum: calculate the given checksum of file
+
+     if extended commands (system.run[*]) are activated,
+     all commands on remote host (accessible to zabbix users) may be called
+
+
 EOF
 }
 
@@ -135,13 +148,6 @@ function zg-k {
    zabbix_get -s $HOST -k "${key}"
 }
 
-# echos 1 if 
-function dir_exists_p {
-    local dirpath="$1"
-    local key="vfs.file.exists[${dirpath},dir]"
-
-    zg-k "$key"
-}
 
 # FIXME: carefully handle quoting
 function zg_sr {
@@ -151,6 +157,15 @@ function zg_sr {
     zg-k "$key"
 }
 
+# FIXME: should be factorized 
+function pathname_exists_p {
+    local dirpath="$1"
+    local kind="${2:-file}"
+    
+    local key="vfs.file.exists[${dirpath},${kind}]"
+
+    zg-k "$key"
+}
 
 # ==============================================================================
 #  MAIN
@@ -170,7 +185,7 @@ while getopts "hV" flag "$@"
 do
     case $flag in
 	h) usage && exit 0 ;;
-	V) echo "$PROGNAME: $VERSION" && exit 0 ;;
+	V) echo "$SCRIPTNAME: $VERSION" && exit 0 ;;
 
 	*) exit 1 ;;
     esac
@@ -178,7 +193,7 @@ done
 
 # Does agent respond on specified target?
 zabbix_get -t $TIMEOUT -s $HOST -k agent.ping >/dev/null
-[[ $? -ne 0 ]] && echo "$PROGNAME[agent.ping]: error: agent did respond on time, exiting..." && exit 2
+[[ $? -ne 0 ]] && echo "$SCRIPTNAME[agent.ping]: error: agent did respond on time, exiting..." && exit 2
 
 # Does agent support proc.get key? (only recent versions)
 agent_version=$(zabbix_get -t $TIMEOUT -s $HOST -k agent.version)
@@ -206,11 +221,8 @@ display_welcome_message
 while true
 do
     echo -e "$(colored $PROMPT $BRIGHT)\c"
-    read input
-    #read
-
-    [[ -n $DEBUG ]] && echo "input='$input'"
-    echo $input | read cmd arg1 arg2 arg3 arg4
+    read cmd arg1 arg2 arg3 arg4 arg5
+    
     [[ -n $DEBUG ]] && echo "cmd='$cmd' arg1='$arg1' arg2='$arg2' arg3='$arg3'"
     
     # Better used with implicit $* arguments?
@@ -228,19 +240,21 @@ do
 		     *) CWD=$CWD/$arg1 ;; #FIXME: add check of existence !!
 		esac
 	    # FIXME: tests if exists!!
-	    if [[ $(dir_exists_p "$CWD") -ne 1 ]]; then
-		echo "$PROGNAME: $CWD does not exist on remote host!!"
+	    if [[ $(pathname_exists_p "$CWD" dir) -ne 1 ]]; then
+		echo "$SCRIPTNAME: $CWD does not exist on remote host!!"
 		CWD=$OLDCWD
 	    fi
+	    
 	    # FIXME: check validity of hack!!
 	    [[ $CWD != "/" ]] && CWD=$(echo $CWD | perl -pe 's@(/+)@/@g')
 	    echo $CWD
 	    ;;
 	
-	cat) case $arg1 in
+	cat)
+	    case $arg1 in
 		    /*) pathname=$arg1 ;;
 		     *) pathname=$CWD/$arg1 ;; #FIXME: add check of existence !!
-	     esac
+	    esac
 	    #zabbix_get -s $HOST -k "vfs.file.contents[$pathname]"
 	    zg-k "vfs.file.contents[$pathname]"
             ;;
@@ -256,18 +270,19 @@ do
 
 	ll)
 	    # | mlr --j2t cat | tabulate -1 -f pipe
-	    zg-k "vfs.dir.get[$CWD,,,,,0]" | jq -cMr ".[] | $JQ_LL_EXTRACTOR" | mlr --j2t cat | tabulate -1 -f plain
-	    ;;
+	    zg-k "vfs.dir.get[$CWD,,,,,0]" | jq -cMr ".[] | $JQ_LL_EXTRACTOR" | mlr --j2t cat | tabulate -1 -f ${GRID_STYLE} ;;
 
 	ltr) # FIXME: fix duplication with 
-	    zg-k "vfs.dir.get[$CWD,,,,,0]" | jq -cMr ". | sort_by(.time.change) | .[] | $JQ_LL_EXTRACTOR" | mlr --j2t cat | tabulate -1 -f plain
+	    zg-k "vfs.dir.get[$CWD,,,,,0]" | jq -cMr ". | sort_by(.time.change) | .[] | $JQ_LL_EXTRACTOR" | mlr --j2t cat | tabulate -1 -f ${GRID_STYLE}
 	    ;;
  
 	# ----------------------------------------------------------------------
-	ps)	echo "NOT YET IMPLEMENTED..." ;;
+	ps) # FEATURE: handle us and aux
+	    zg-k "proc.get" | jq -cMr ". | sort_by(${JQ_PS_SORT_KEY}) | .[] | $JQ_PS_EXTRACTOR" | mlr --j2t cat | tabulate -1 -f ${GRID_STYLE}
+	    ;;
 
 	# ----------------------------------------------------------------------
-	top)	echo "NOT YET IMPLEMENTED..." ;;
+	top) echo "NOT IMPLEMENTED, YET..." ;;
 
 	# ----------------------------------------------------------------------
 	cksum|md5sum)
@@ -299,11 +314,14 @@ do
 	help)		help ;;
 
 	# ------------------------------------------------------------------------
-	# Detection of zabbix keys
-	agent.*|kernel.*) echo "Zabbix Agent key: NOT IMPLEMENTED YET..." ;;
+	# DIRECT CALL of zabbix keys
+	# in case key is not recognized we have a simple direct message
+	agent.*|kernel.*|net.*|proc.*|system.*|vfs.*)
+	    zg-k "$cmd"
+	    ;;
 	
 	# ------------------------------------------------------------------------
-	"")		: ;; # handle useless use of 'Enter' key
+	"")		: ;; # handle pointless press of 'Enter' key
 	
 	*)   if [[ ! -z $EXTENDED_COMMANDS ]]; then
 	       # FIXME: handle CWD
@@ -317,7 +335,4 @@ done
 [[ -z $DEBUG ]] && cleanup
 
 exit $current_rc
-
-
-
 
